export const mySkills = [
  { title: 'Java', icon: 'javascript' },
  { title: 'Python', icon: 'postman' },
  { title: 'JavaScript', icon: 'javascript' },
  { title: 'SQL', icon: 'database' },
  { title: 'React.js', icon: 'react' },
  { title: 'HTML', icon: 'html' },
  { title: 'CSS', icon: 'css' },
  { title: 'Node.js', icon: 'nodejs' },
  { title: 'REST APIs', icon: 'express' },
  { title: 'MongoDB', icon: 'mongodb' },
  { title: 'MySQL', icon: 'database' },
  { title: 'Git', icon: 'git' },
  { title: 'GitHub', icon: 'gitHub' },
  { title: 'Vercel', icon: 'vercel' },
  { title: 'Render', icon: 'vercel' },
  { title: 'Data Structures', icon: 'database' },
  { title: 'OOP', icon: 'database' },
  { title: 'DBMS', icon: 'database' },
  { title: 'Operating Systems', icon: 'database' },
  { title: 'CNN', icon: 'database' },
  { title: 'SSD-ResNet', icon: 'database' },
  { title: 'OpenCV', icon: 'database' },
  { title: 'ML Libraries', icon: 'database' },
];
